### ISSUE TITLE
List of building blocks

### ISSUE THREAD

**Issue by theo-cox** [life-itself/diginomics#32]
Building blocks for incentive models

## Acceptance

- [x] List of building blocks and agreed terminology
- [x] Descriptions of the blocks
- [x] Visual representation of how they fit together/relate to one another

**All these are now included in the /concepts.md page: https://github.com/life-itself/diginomics/blob/main/content/notes/concepts.md**

**Comment by theo-cox** [comment]
@rufuspollock Having brainstormed I've reached a stage where it would be helpful to talk through together. See from p7 of doc here for my ideas: https://docs.google.com/document/d/1VzlQw2WSVNoSBqzRzJUSyZn8AJL5M0CtXBP1BuIkdyA/edit?usp=sharing

**Comment by rufuspollock** [comment]
@theo-cox i think this is pretty good. I do wonder if doing a case stuff or two here (or even made-up examples) would really help us and the reader. It can seem a bit abstract and overwhelming at first glance. 

It's good to have the comprehensive list ... and i wonder if we can start with something simple and build up e.g. the two key options. e.g. it seems to me we can discard "non-financial" options in many cases to a great extent. (BTW i count complementary good as financial - it just isn't direct ...).

For example, perhaps two basic building blocks are:

- openness / closedness
- revenue source

??

As i said, perhaps a quick list of examples (or even exemplars) would be really helpful ...

**Comment by rufuspollock** [comment]
We have done a lot of work on this in the last few weeks and have close to final version in https://diginomics.io/notes/concepts and also in #67

**Comment by rufuspollock** [comment]
@theo-cox what's remaining on this one?

**Comment by theo-cox** [comment]
FIXED. We did all this and posted here: https://github.com/life-itself/diginomics/blob/main/content/notes/concepts.md
