### ISSUE TITLE
Terminology and Glossary

### ISSUE THREAD

**Issue by theo-cox** [life-itself/diginomics#39]
When discussing what we are doing especially re design of "models" it would be helpful to have clear set of terminology so that we and others don't get confused (e.g. what is a model)

## Acceptance

- [x] List of ideas/concepts we use (even if with "wrong" names or no names just descriptions) **✅2023-03-27 see https://link.excalidraw.com/l/9u8crB2ZmUo/vpDJPY8Yp5 and below**
- [x] Identify key ones
- [x] choose names for them (at least for now) and short definitions
- [x] Terminology / glossary page of definitions on the site at `/glossary/` (this is just definitions of key terms so we can link from other places on the site) **DONE: https://github.com/life-itself/diginomics/blob/main/content/notes/glossary.md**
- [x] (maybe) separate `/concepts/` page with the text and the diagrams (or maybe for now just a blog post keeping with our "notes" approach and publish early and often - later when solidified we can convert into a specific page) **This is fairly comparable to above and for ease I suggest we just have 1 page**

### 2023-03-27

This is a guide for **designers** of **business models** for **digital goods**. It shows how business models are composed of building **blocks** which can be assembled under **constraints** to make a limited number of business model **types**. Learning these types -- and the list of blocks and the rules for assembly -- allow you to rapidly design business models that are **successful** for your chosen **outcomes**. 

-   Designers such as entrepreneurs, policy-makers, commons cultivators! ...
-   Outcomes e.g. increasing welfare or making money -- or inputs to those such as revenue and access.
	-   Features e.g. access [open | closed | semi-open]
-   Blocks: such as revenue sources and how you build the good] 
-   Limited types: because there are a limited number of options for each block and there are constraints
-   Business model [for digital goods] is a XXX for the production and distribution of digital goods TODO: ecosystem would be a better term but we use business model for XX reason
	-   Aka:  value ecosystem
-   Digital good: data or information or ... 
	-   Aka: information goods, information product etc etc

#### How the pieces fit together

https://link.excalidraw.com/l/9u8crB2ZmUo/vpDJPY8Yp5

![image](https://user-images.githubusercontent.com/180658/227934499-40e284ca-76dc-4a78-bb0f-c7d36fffb695.png)

#### Options for terms

![image](https://user-images.githubusercontent.com/180658/227934806-b36630b8-6301-4491-98a9-d9659ed849dd.png)

### first brainstorm

- Mental model: How you’re thinking about the world; the features you attribute to objects in your mind.
- Systems: (Types of) [models/options]: The types of [digital economic systems]. A system includes the incentives, institutions and value flows around the production and supply of digital goods.
- Ingredients [blocks]: The specific components of these systems e.g. the incentive mechanisms, the key stakeholders, the allocation mechanisms.

**Theo 27/03/2023: Think the mental model vs system distinction works and should stick. Prefer building blocks to ingredients. 
Q: System vs mechanism?**

### 2023-01-31: An example of us overloading the term "model"

- STEP 1: Check your mental model (it matters!) Digital/data is fundamentally different (from what!). Check your (old) “mental models” at the door.
- STEP 2: Understand the basic model for a digital economic system. Take a quick 30,000 ft tour of the incentives and value flows in a digital economic system (this is going to matter in the next step!)
- STEP 4: Start simple. Get to grips with 5 basic models and their constraints.

**Comment by rufuspollock** [comment]
@theo-cox just updated issue description with outputs of the brainstorming including images and updated acceptance.

Aside: btw if we do publish posts better to use svgs and post versions in local excalidraw - though i can do this later and you just steam ahead with github pngs for now.

**Comment by theo-cox** [comment]
Updated with draft page which is in progress here: https://docs.google.com/document/d/1EeSe9e0fmelrh7Ke6DNlX227bynzKzsK9dly5uaDuVE/edit?usp=sharing

**Comment by theo-cox** [comment]
Created https://github.com/life-itself/diginomics/blob/main/content/notes/glossary.md and suggest this acts as both the glossary and concepts page for ease. Leaving open until your review @rufuspollock

**Comment by theo-cox** [comment]
FIXED. For completeness I also created a blog (which links out to the glossary) here: https://github.com/life-itself/diginomics/blob/main/content/notes/combining-pieces.md

**Comment by rufuspollock** [comment]
Great work in moving this forward.

## Glossary or not ...

> Created [`main`/content/notes/glossary.md](https://github.com/life-itself/diginomics/blob/main/content/notes/glossary.md?rgh-link-date=2023-03-28T13%3A34%3A44Z) and suggest this acts as both the glossary and concepts page for ease. Leaving open until your review @rufuspollock

This isn't really a glossary as it stands - more a concepts page. I think probably better just to call it that for now.

## Blog post

> FIXED. For completeness I also created a blog (which links out to the glossary) here: [main/content/notes/combining-pieces.md](https://github.com/life-itself/diginomics/blob/main/content/notes/combining-pieces.md?rgh-link-date=2023-03-28T13%3A51%3A09Z)

Great. Good to ship. In terms of title, how about: `Building Business Models: A Framework v1-alpha` (the `v1-alpha` is geeky an optional!)

I think we could also add a bit more content there to explain a bit more but not entirely necessary.

PS: bonus for using svgs or even local excalidraw files!

## Formatting errors

There's a fair number of minor markdown formatting errors - are you editing this in obsidian? (such formatting errors should be obvious there).

![image](https://user-images.githubusercontent.com/180658/228426700-8d148ddf-9e6f-4b07-ac94-a6f6768f5761.png)

## PS: using pull requests

I wonder if we could start doing pull requests which would allow me to provide you much more helpful (b/c specific) feedback

**Comment by theo-cox** [comment]
@rufuspollock 1) made changes to glossary pages and fixed errors. 2) made title change to blog. 3) I'm using docs to markdown which seems to be the problem for whatever reason annoyingly. 4) I'll do PRs from now on and have done 1 and 2 via PR to that end.

**Comment by theo-cox** [comment]
Going to redo this page in line with review and discussion on building block shift
