### ISSUE TITLE
Schematic and terminology for information good economic ecosystem

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#45]
Information good economic ecosystem diagram (money from where, to where): defining key terms – see https://link.excalidraw.com/l/9u8crB2ZmUo/AS49XMqTYbf

![image](https://user-images.githubusercontent.com/180658/227154252-1787a952-e505-4fc1-a226-5afd0328bba7.png)

## Acceptance

- [x] Draft diagram
- [x] Published note / post about it **https://github.com/life-itself/diginomics/blob/main/content/notes/digital-ecosystem.md**

**Comment by theo-cox** [comment]
FIXED. Published here; https://github.com/life-itself/diginomics/blob/main/content/notes/digital-ecosystem.md

**Comment by rufuspollock** [comment]
@theo-cox good - i think we do want to do a bit of tweaking of that diagram - so maybe this would be best titled in blog section as something like "Overview of a digital good [diginomics?] ecosystem (First Draft)"

Specifically i think we want to try out a few iterations e.g. one where we group inflows of money, inflows of inputs etc.

But maybe we open a follow up issue e.g. ecosystem diagram v1.1 or something!
